# Generated by Django 5.2.15 on 2026-06-11 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=150, unique=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_payload', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=320)),
                ('otp_type', models.CharField(choices=[('email_verification', 'email_verification'), ('password_reset', 'password_reset')], max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='accounts.user')),
            ],
            options={
                'db_table': 'otp_codes',
                'constraints': [models.UniqueConstraint(fields=('email', 'otp_type'), name='uq_otp_codes_email_type')],
            },
        ),
    ]
