# Generated by Django 5.2.15 on 2026-06-11 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
