# Generated by Django 5.2.15 on 2026-06-11 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('squad_transaction_ref', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('complete', 'complete'), ('error', 'error')], default='pending', max_length=20)),
                ('verdict', models.CharField(blank=True, choices=[('AUTHENTIC', 'AUTHENTIC'), ('NEEDS REVIEW', 'NEEDS REVIEW'), ('FAKE', 'FAKE')], max_length=20, null=True)),
                ('trust_score', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.user')),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
    ]
